export const SET_USER_INFO = "SET_USER_INFO";
export const SET_SHOW_SIGNUP = "SET_SHOW_SIGNUP";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const SET_DATA_USER = "SET_DATA_USER";

export const SET_LOADING = "SET_LOADING";

export const SET_MODAL = "SET_MODAL";

export const SET_LIST_USER = "SET_LIST_USER";
export const SET_LIST_TASK = "SET_LIST_TASK";

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export const GET_PROJECTS_DATA = "GET_PROJECTS_DATA";

export const SET_KEYWORD_SEARCH_USER = "SET_KEYWORD_SEARCH_USER";
export const SET_RESULT_SEARCH_USER = "SET_RESULT_SEARCH_USER";
